name: JoinLeaveMessages
version: '${project.version}'
main: com.pudgio.dev.joinleavemessages.JoinLeaveMessages
api-version: 1.18
authors: [ pudgio ]
description: Changes the servers join and leave messages for players.
